// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _5._1_Desafio_do_curso.Data;

#nullable disable

namespace _5._1_Desafio_do_curso.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_5._1_Desafio_do_curso.Entities.ContaPF", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.ToTable("ContaPFs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ContaPF");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_5._1_Desafio_do_curso.Entities.ContaPJ", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.ToTable("ContaPJs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ContaPJ");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_5._1_Desafio_do_curso.Entities.ExtratoPF", b =>
                {
                    b.HasBaseType("_5._1_Desafio_do_curso.Entities.ContaPF");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoOp")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ExtratoPF");
                });

            modelBuilder.Entity("_5._1_Desafio_do_curso.Entities.ExtratoPJ", b =>
                {
                    b.HasBaseType("_5._1_Desafio_do_curso.Entities.ContaPJ");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoOp")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ExtratoPJ");
                });
#pragma warning restore 612, 618
        }
    }
}
